CREATE TABLE tasks (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  business_id bigint(20) NOT NULL,
  business_unique_id varchar(128) NOT NULL,
  callback_url varchar(512) NOT NULL,
  callback_method varchar(10) NOT NULL DEFAULT 'POST',
  callback_headers text,
  callback_body text,
  retry_intervals varchar(256) NOT NULL DEFAULT '[60,300,900]',
  max_retries int(11) NOT NULL DEFAULT 3,
  current_retry int(11) NOT NULL DEFAULT 0,
  status tinyint(4) NOT NULL DEFAULT 0,
  priority tinyint(4) NOT NULL DEFAULT 5,
  tags varchar(512) DEFAULT NULL,
  timeout int(11) NOT NULL DEFAULT 30,
  scheduled_at timestamp NOT NULL,
  next_execute_at timestamp NULL DEFAULT NULL,
  executed_at timestamp NULL DEFAULT NULL,
  completed_at timestamp NULL DEFAULT NULL,
  error_message text,
  metadata text,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_business_task (business_id, business_unique_id),
  KEY idx_status (status),
  KEY idx_priority (priority),
  KEY idx_next_execute_at (next_execute_at),
  KEY idx_scheduled_at (scheduled_at),
  KEY idx_business_id_status (business_id, status),
  KEY idx_created_at (created_at),
  CONSTRAINT fk_tasks_business_id FOREIGN KEY (business_id) REFERENCES business_systems (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;